---
version: "2.1"
services:
  calibre-web:
    # image: lscr.io/linuxserver/calibre-web:latest
    #image: lscr.io/linuxserver/calibre-web:nightly
    build: .
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - CALIBRE_UNIX_SOCKET=/config/www.sock
      - DOCKER_CALIBRE_SERVER_CLI=--enable-local-write --userdb /config/serverdb.db --enable-auth --auth-mode=basic --trusted-ips=172.25.0.1 --url-prefix=/cbs
    volumes:
      - /srv/services/calibreweb-config:/config
      - /srv/services/calibreweb-books:/books
    ports:
      - 127.0.0.1:8082:8080
    restart: unless-stopped
